spring:
  application:
    name: habit-money

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

app:
  jwt:
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

logging:
  level:
    com.nikhil: DEBUG
    org.springframework.security: DEBUG
