spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/habit_money
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  jwt:
    secret: ${DEV_JWT_SECRET}
  google:
    client-id: ${DEV_GOOGLE_CLIENT_ID}
